# Generate api-worker/.dev.vars, .env.local, hermes-railway/.env.docker.local
param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$ErrorActionPreference = "Stop"
$secretsFile = Join-Path $RepoRoot "local.dev.secrets.env"
if (-not (Test-Path $secretsFile)) {
  throw "Missing local.dev.secrets.env (edit in repo root, then re-run)."
}

function Read-DotEnv([string]$Path) {
  $map = @{}
  Get-Content $Path -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#")) { return }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { return }
    $k = $line.Substring(0, $idx).Trim()
    $v = $line.Substring($idx + 1).Trim()
    $map[$k] = $v
  }
  return $map
}

function Require-Key($map, [string]$Key) {
  $v = ""
  if ($map.ContainsKey($Key)) { $v = $map[$Key] }
  $v = $v.Trim()
  if (-not $v -or $v -match "replace-with-your|change-me") {
    throw "Set a valid value in local.dev.secrets.env: $Key"
  }
  return $v
}

function Require-SecretKey($map, [string]$Key) {
  $v = Require-Key $map $Key
  if ($v.Length -lt 16) {
    throw "local.dev.secrets.env: $Key must be at least 16 characters (Hermes refuses shorter keys on 0.0.0.0). Current length: $($v.Length)"
  }
  return $v
}

$cfg = Read-DotEnv $secretsFile
$llmBase = Require-Key $cfg "LLM_API_BASE_URL"
$llmKey = Require-Key $cfg "LLM_API_KEY"
$llmModel = Require-Key $cfg "LLM_MODEL"
$tavily = Require-Key $cfg "TAVILY_API_KEY"
$hermesKey = Require-SecretKey $cfg "HERMES_API_KEY"
$jfoInternal = Require-SecretKey $cfg "JFO_INTERNAL_KEY"
$defaultUser = "jimmy-huang"
if ($cfg.ContainsKey("JFO_DEFAULT_USER_ID") -and $cfg["JFO_DEFAULT_USER_ID"].Trim()) {
  $defaultUser = $cfg["JFO_DEFAULT_USER_ID"].Trim()
}

$mysqlBlock = ""
if ($cfg.ContainsKey("MYSQL_HOST") -and $cfg["MYSQL_HOST"].Trim()) {
  $mysqlHost = $cfg["MYSQL_HOST"].Trim()
  $mysqlPort = if ($cfg.ContainsKey("MYSQL_PORT") -and $cfg["MYSQL_PORT"].Trim()) { $cfg["MYSQL_PORT"].Trim() } else { "3306" }
  $mysqlUser = Require-Key $cfg "MYSQL_USER"
  $mysqlPass = Require-Key $cfg "MYSQL_PASSWORD"
  $mysqlDb = Require-Key $cfg "MYSQL_DATABASE"
  $dbDriver = if ($cfg.ContainsKey("DB_DRIVER") -and $cfg["DB_DRIVER"].Trim()) { $cfg["DB_DRIVER"].Trim() } else { "mysql" }
  $mysqlBlock = @"

DB_DRIVER=$dbDriver
MYSQL_HOST=$mysqlHost
MYSQL_PORT=$mysqlPort
MYSQL_USER=$mysqlUser
MYSQL_PASSWORD=$mysqlPass
MYSQL_DATABASE=$mysqlDb
MYSQL_BRIDGE_URL=http://127.0.0.1:8790
"@
}

$minioBlock = ""
if ($cfg.ContainsKey("MINIO_ENDPOINT") -and $cfg["MINIO_ENDPOINT"].Trim()) {
  $minioEndpoint = $cfg["MINIO_ENDPOINT"].Trim().TrimEnd("/")
  $minioAccess = Require-Key $cfg "MINIO_ACCESS_KEY"
  $minioSecret = Require-Key $cfg "MINIO_SECRET_KEY"
  $minioBucket = Require-Key $cfg "MINIO_BUCKET"
  $fileDriver = if ($cfg.ContainsKey("FILE_DRIVER") -and $cfg["FILE_DRIVER"].Trim()) { $cfg["FILE_DRIVER"].Trim() } else { "minio" }
  $minioRegion = if ($cfg.ContainsKey("MINIO_REGION") -and $cfg["MINIO_REGION"].Trim()) { $cfg["MINIO_REGION"].Trim() } else { "us-east-1" }
  $minioMaxBytes = if ($cfg.ContainsKey("MINIO_MAX_UPLOAD_BYTES") -and $cfg["MINIO_MAX_UPLOAD_BYTES"].Trim()) { $cfg["MINIO_MAX_UPLOAD_BYTES"].Trim() } else { "52428800" }
  $minioBlock = @"

FILE_DRIVER=$fileDriver
MINIO_ENDPOINT=$minioEndpoint
MINIO_ACCESS_KEY=$minioAccess
MINIO_SECRET_KEY=$minioSecret
MINIO_BUCKET=$minioBucket
MINIO_REGION=$minioRegion
MINIO_MAX_UPLOAD_BYTES=$minioMaxBytes
"@
}

$workerDevVars = @"
# Auto-generated by scripts/generate-local-config.ps1
DASHSCOPE_API_KEY=$llmKey
DASHSCOPE_BASE_URL=$llmBase
TAVILY_API_KEY=$tavily

HERMES_BASE_URL=http://127.0.0.1:8642
HERMES_API_KEY=$hermesKey
HERMES_MODEL=$llmModel
HERMES_RESTART_MODE=docker
HERMES_DOCKER_CONTAINER=jfo-hermes-local
ALLOWED_ORIGIN=http://localhost:5173

JFO_INTERNAL_KEY=$jfoInternal
JFO_API_PUBLIC_BASE=http://127.0.0.1:8787$mysqlBlock$minioBlock
"@

$frontendEnv = @"
# Auto-generated by scripts/generate-local-config.ps1
VITE_ENABLE_LIVE_CHAT=1
VITE_AI_CHAT_ENDPOINT=http://127.0.0.1:8787/api/chat
"@

$hermesData = Join-Path $env:USERPROFILE ".jfo-local\hermes"
New-Item -ItemType Directory -Force -Path $hermesData | Out-Null

$hermesDockerEnv = @"
# Hermes container env (volume: $hermesData -> /opt/data)
API_SERVER_ENABLED=true
API_SERVER_HOST=0.0.0.0
API_SERVER_KEY=$hermesKey
OPENAI_API_BASE=$llmBase
OPENAI_API_KEY=$llmKey
MODEL_DEFAULT=$llmModel
JFO_API_PUBLIC_BASE=http://host.docker.internal:8787
JFO_INTERNAL_KEY=$jfoInternal
JFO_DEFAULT_USER_ID=$defaultUser
"@

Set-Content -Path (Join-Path $RepoRoot "api-worker\.dev.vars") -Value $workerDevVars.TrimEnd() -Encoding UTF8
Set-Content -Path (Join-Path $RepoRoot ".env.local") -Value $frontendEnv.TrimEnd() -Encoding UTF8
Set-Content -Path (Join-Path $RepoRoot "hermes-railway\.env.docker.local") -Value $hermesDockerEnv.TrimEnd() -Encoding UTF8

Write-Host "Generated:" -ForegroundColor Green
Write-Host "  api-worker/.dev.vars"
Write-Host "  .env.local"
Write-Host "  hermes-railway/.env.docker.local"
